<?php

return array(
    'dear-member' => 'Dear ^MEMBER_NAME^',
    'enter-pin' => 'Please enter your Virtue Ghana Secret PIN',
    'invalid-pin' => 'You entered a wrong PIN',
    'welcome-customer' => 'Welcome to Virtue Ghana', 
    
    //Menu options
    'loan-eligibility-option' => '1. Check eligible amount',
    'menu-1' => '2. Request for Loan',
    'menu-2' => "3. Check loan status",
    'menu-3' => "4. Account mini statement",
    'menu-4' => '5. My member profile',
    'exit' => '00. Main Menu',
    'main-menu' => 'Main Menu',
    'choose-option' => 'Choose Option',
    'logout' => '99. Exit',
    'select-loan-option' => 'Select Loan Option',
    'request-loan' => '1. Request for a Loan',
    'repay-loan' => '2. Re-pay Loan',
    'check-limit' => '3. Check loan limit',
    'main-menu' => '00. Main Menu',
    'enter-loan-amount' => 'Please enter loan amount of between ^MAX^ and ^MIN^',
    'pay-back-loan' => 'To pay back loan please dial *919#',
    'loan-processed' => 'Your loan request has been received and is being processed.',
    'received-1' => 'You have received cedi ',
    'received-2' => 'kuri konti yawe ya Virtue Ghana',
    'invalid-option' => 'Invalid option,',
    'logout-text' => 'Thank you for choosing Virtue Ghana, Bye!',
    'service-unavailable' => 'Requested service is currently unavailable',
    'account-to-be-activated' => 'Your Account will be activated shortly and you will receive an SMS with your new PIN. Thank you',    
    'error-activating-account' => 'We could not activate your account, contact your association head or Virtue Ghana customer care',
    'activation-sms' => 'Dear ^MEMBER_NAME^, your Virtue Ghana account has been activated. Your SECRET PIN is ^PIN^. Dial *919#',
    'member-details' => 'Member details',
    'min-max-amount' => 'Enter loan amount between cedi 500 and cedi 1000',
    'pending-loan-request' => 'Dear member, you have a pending loan request. Please wait as we process the loan',
    'not-registered-welcome' => 'Dear member, Kindly visit your association office to register for Virtue Ghana and access mobile loans',
    'association' => 'Association',
    'date-registered' => 'Date registered',
    'no-existing-transactions' => 'Dear customer, you do not have any transactions',
    'mini-statement' => 'Account mini statement',
    'no-existing-loan' => 'Dear customer, you have no existing loans',
    'loan-in-process' => 'Your initial loan request of ^CURRENCY_CODE^ ^AMOUNT^ is being processed and will get a notification when approved',
    'loan-processed' => 'Your loan request of ^CURRENCY_CODE^ ^AMOUNT^ has been approved. You will receive the money shortly via mobile money',
    'loan-rejected' => 'Your loan request of ^CURRENCY_CODE^ ^AMOUNT^ was rejected. Please try again at a later time',
    'loan-exported' => 'Your loan request of ^CURRENCY_CODE^ ^AMOUNT^ is being processed, you will receive the money within 2-3 on MTN mobile money',
    'loan-logged' => 'Your loan request of ^CURRENCY_CODE^ ^AMOUNT^ has been received and is being processed. You will get a confirmation message shortly',
    'error-check-gl-account' => 'Dear member, their was an error checking your account. Contact your association code. Ref code: 404',
    'have-loan' => 'Dear member, you have an existing loan. Kindly clear your current loan of ^CURRENCY_CODE^ ^AMOUNT^ and increase your loan limits',
    'have-loan-awaiting-approval' => 'Dear member, your loan request of ^CURRENCY_CODE^ ^AMOUNT^ is awaiting approval. You will get a confirmation message',
    'have-loan-awaiting-disburse' => 'Dear member, your loan request of ^CURRENCY_CODE^ ^AMOUNT^ has been approved will be sent to you via Mobile money in 2-3 hours',
    'min-max-qualified' => 'Dear member, you qualify for loans from cedi ^MIN_AMOUNT^ to cedi ^MAX_AMOUNT^',
    'confirm-loan-request' => "Dear member, You have requested for loan of cedi ^AMOUNT^ \n1. Confirm",
    
    
    //Authentication
    'account-blocked' => 'You have entered an incorrect PIN more than three times, Account has been blocked. Try again after 5 minutes',
    'account-is-blocked' => 'Your account is blocked. Kindly visit your association for help with resetting your account',
    
    'error-processing-request' => 'We encountered an error while processing your request. Please try again later',
);