<?php

return array(
    'dear-member' => 'Dear ^MEMBER_NAME^',
    'enter-pin' => 'Shyiramo PIN ya Kwigira',
    'invalid-pin' => 'Wibeshye PIN',
    'welcome-customer' => 'Ikaze muri Kwigira', 
    
    //Menu options
    'loan-eligibility-option' => '1.Reba amafaranga wemerewe gusaba',
    'menu-1' => '2.Gusaba Inguzanyo',
    'menu-2' => "3.Amakuru kuri Konti",
    'menu-3' => "4.Raporo Ngufi",
    'menu-4' => '5.Konti ya Kwigira',
    'exit' => '00.Intangiriro',
    'main-menu' => 'Intangiriro',
    'choose-option' => 'Hitamo',
    'logout' => '99.Sohokamo',
    'select-loan-option' => 'Hitamo Inguzanyo',
    'request-loan' => '1.Gusaba Inguzanyo',
    'repay-loan' => '2.Kwishyura inguzanyo',
    'check-limit' => '3.Reba inguzanyo ntarengwa',
    'main-menu' => '00.Intangiriro',
    'enter-loan-amount' => 'Shyiramo umubare winguzanyo wifuza hagati ya Rwf ^MIN^ NA Rwf ^MAX^',
    'pay-back-loan' => 'Kwishyura inguzanyo kanda *919#',
    'loan-processed' => 'Inguzanyo wasabye yakiriwe,Birimo gukorwa',
    'received-1' => 'Wakiriye amafaranga',
    'received-2' => 'kuri konti yawe ya Kwigira',
    'invalid-option' => 'Ibyo musabye ntibishoboye gukunda',
    'logout-text' => 'Murakoze guhitamo Kwigira',
    'service-unavailable' => 'Ibyo musabye ntibishoboye kuboneka',
    'account-to-be-activated' => 'Konti yawe irafungurwa mu mwanya muto.Murabona PIN mu butumwa bugufi.Murakoze',    
    'error-activating-account' => 'Konti ntiyafunguwe.Egera ishyirahamwe ryawe cyangwa Kwigira costumer care',
    'activation-sms' => '^MEMBER_NAME^, Konti ya Kwigira yafunguwe. PIN yawe ni ^PIN^. Kanda *919#',
    'member-details' => 'Imyirondoro',
    'min-max-amount' => 'Shyiramo umubare winguzanyo hagati ya 10000 na 30000',
    'pending-loan-request' => '',
    'not-registered-welcome' => 'Mukiriya wacu,Egera ishyirahamwe ryawe Wiyandikishe muri kwigira kugirango ubashe gusaba inguzanyo',
    'association' => 'Ishyirahamwe',
    'date-registered' => 'Itariki Mwiyandikishijeho',
    'no-existing-transactions' => 'Mukiriya wacu,nta Bikorwa mufite',
    'mini-statement' => 'Raporo Ngufi',
    'no-existing-loan' => 'Mukiriya wacu,nta deni mufite',
    'loan-in-process' => 'Inguzanyo musabye ya ^CURRENCY_CODE^ ^AMOUNT^ iri gukorwa.Urabona ubutumwa bugufi nibyemezwa',
    'loan-processed' => 'Inguzanyo musabye ya ^CURRENCY_CODE^ ^AMOUNT^ yemejwe.Murakire amafaranga kuri mobile money mu mwanya muto',
    'loan-rejected' => 'Inguzanyo musabye ya ^CURRENCY_CODE^ ^AMOUNT^ ntiyemejwe.Mwongere mukanya',
    'loan-exported' => 'Inguzanyo musabye ya ^CURRENCY_CODE^ ^AMOUNT^ irimo gukorwa.Urakira amafaranga kuri Mtn Mobile Money yawe musaha 2-3',
    'loan-logged' => 'Inguzanyo musabye ya ^CURRENCY_CODE^ ^AMOUNT^ yakiriwe, irimo gukorwa.Murabona ubutumwa bugufi mukanya gato',
    'error-check-gl-account' => '',
    'have-loan' => 'Mukiriya wacu,Mufite ideni ritarishyurwa,Mwishyure ideni rya  ^CURRENCY_CODE^ ^AMOUNT^ kugirango Mushobora guhabwa inguzanyo y amafaranga yisumbuyeho',
    'have-loan-awaiting-approval' => '',
    'have-loan-awaiting-disburse' => '',
    'min-max-qualified' => 'Mukiriya wacu,Mwemerewe inguzanyo iri hagati ya  ^MIN_AMOUNT^ to Rwf ^MAX_AMOUNT^',
    'confirm-loan-request' => "Mukiriya wacu,Wasabye inguzanyo ya  ^AMOUNT^\n1.Kwemeza",    
    //Authentication
    'account-blocked' => 'Wibeshye PIN inshuro zirenga eshatu.Konti yawe yafunzwe,Wongere nyuma yiminota 5',
    'account-is-blocked' => 'Konti yanyu yafunzwe.Mwegere ishyirahamwe ryanyu babafasha kongera kuyifungura.',    
    'error-processing-request' => 'Habayemo ikibazo mugihe mwasabaga inguzanyo.Mwongere mukanya',
);